-- Create Playlists Table
create table "public"."playlists" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "name" text not null,
    "image_path" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key ("id"),
    foreign key ("user_id") references auth.users("id") on delete cascade
);

-- Enable RLS
alter table "public"."playlists" enable row level security;

-- Create Policies for Playlists (Private by Default)
create policy "Users can view their own playlists"
on playlists for select using (auth.uid() = user_id);

create policy "Users can insert their own playlists"
on playlists for insert with check (auth.uid() = user_id);

create policy "Users can update their own playlists"
on playlists for update using (auth.uid() = user_id);

create policy "Users can delete their own playlists"
on playlists for delete using (auth.uid() = user_id);


-- Create Playlist Songs Join Table
create table "public"."playlist_songs" (
    "playlist_id" bigint not null,
    "song_id" bigint not null,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key ("playlist_id", "song_id"),
    foreign key ("playlist_id") references playlists("id") on delete cascade,
    foreign key ("song_id") references songs("id") on delete cascade
);

-- Enable RLS
alter table "public"."playlist_songs" enable row level security;

-- Create Policies for Playlist Songs
create policy "Users can view songs in their playlists"
on playlist_songs for select using (
  auth.uid() in (select user_id from playlists where id = playlist_id)
);

create policy "Users can add songs to their playlists"
on playlist_songs for insert with check (
  auth.uid() in (select user_id from playlists where id = playlist_id)
);

create policy "Users can remove songs from their playlists"
on playlist_songs for delete using (
  auth.uid() in (select user_id from playlists where id = playlist_id)
);
